In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tf2_basics.WindowSequence import WindowSequence

In [2]:
N = 200000
window_size = 150000
stride = 24
sequence = np.random.rand(N)
# y = np.random.rand(N-window_size+1)
y = np.random.rand(N)
window_sequence = WindowSequence(sequence, y, window_size=window_size, stride=stride, batch_size=32, shuffle=True)

In [4]:
sequence.shape

(200000,)

In [5]:
y.shape

(200000,)

In [7]:
window_sequence.y.shape

(50001,)

In [3]:
batch_x, batch_y = window_sequence.__getitem__(0)
print(batch_x)
print(batch_x.shape, batch_y.shape)

[[0.70221516 0.57875008 0.17361513 ... 0.17953976 0.95658414 0.9567209 ]
 [0.27661401 0.00341657 0.01376281 ... 0.62914834 0.76532361 0.67334589]
 [0.18191715 0.74651363 0.67213941 ... 0.91672402 0.84679492 0.9647124 ]
 ...
 [0.06457677 0.24524859 0.40234797 ... 0.78648186 0.46692456 0.51413822]
 [0.73117778 0.16665069 0.65767434 ... 0.21748176 0.71241333 0.40315945]
 [0.20024857 0.00309559 0.73443624 ... 0.00923543 0.541782   0.74561956]]
(32, 150000) (32, 1)


In [4]:
N = 1234
batch_size = 32
num_batches = N // batch_size + 1
left_batch = N % batch_size
print(f"num_batches: {num_batches}")
print(f"left_batch: {left_batch}")

num_batches: 39
left_batch: 18


In [5]:
a = np.array(np.arange(N))
np.random.shuffle(a)

In [6]:
a.shape

(1234,)

In [7]:
index = 38
batch_a = a[index * batch_size:(index + 1) * batch_size]

In [8]:
batch_a.shape

(18,)

In [9]:
batch_a1 = a[1000:1500]

In [10]:
batch_a1.shape

(234,)

In [11]:
a_list = [_ for _ in range(N)]

In [12]:
batch_a_list = a_list[1000:1500]

In [13]:
len(batch_a_list)

234