In [3]:
import numpy as np

## NumPy seed

np.random() takes [MT19937](https://numpy.org/doc/stable/reference/random/legacy.html) as default RNG.

If seed is not set, returned values will differ every time.

In [23]:
np.random.seed(42)
vals_np = np.random.randint(100, size=20)
vals_np

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37])

## NumPy applied for shuffle

In [49]:
# Always remember to initialize the seed
np.random.seed(42)
N = 10
x = np.arange(N) # [0, 1, 2,...,9]
np.random.shuffle(x)
print(x) # shuffle
np.random.seed(42) # reset the seed
print(np.random.permutation(N))

[8 1 5 0 7 2 9 4 3 6]
[8 1 5 0 7 2 9 4 3 6]


In [42]:
import torch

In [47]:
torch.manual_seed(0)
torch.rand(5)

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])