## TensorFlow Playground

@Date    : Dec-03-20 13:13

@Author  : Kelly Hwong (dianhuangkan@gmail.com)

In [1]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [4]:
a = tf.constant([1,2,3,4], dtype=tf.float32)
b = tf.constant([1,2,3,4], dtype=tf.float32)

In [7]:
 c = a * b # Tensor star multiplication

In [9]:
print(a.shape)
print(b.shape)

(4,)
(4,)


In [17]:
scale = tf.constant([3.])
print(scale)
feature_map = tf.random.uniform((3,3))
print(feature_map)
scale * feature_map # Scalar multiplication

tf.Tensor([3.], shape=(1,), dtype=float32)
tf.Tensor(
[[0.91046655 0.21235406 0.8286859 ]
 [0.21311629 0.71326506 0.7428093 ]
 [0.7502055  0.44474065 0.02663076]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.7313995 , 0.6370622 , 2.4860578 ],
       [0.63934886, 2.1397953 , 2.228428  ],
       [2.2506166 , 1.334222  , 0.07989228]], dtype=float32)>

In [24]:
x = tf.ones(shape=(3,3))
# y = tf.ones(shape=(3,3))
y = 2 * x
print(y)
tf.multiply(x, y)

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [27]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(a)
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print(b)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [30]:
c = tf.matmul(a, b, transpose_b=False)
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [36]:
num_channels = 6
x = tf.ones(shape=(32,1,1,num_channels))
y = 2 * tf.ones(shape=(32,3,4,num_channels))
print(x.shape)
print(y.shape)

(32, 1, 1, 6)
(32, 3, 4, 6)


In [37]:
x * y

<tf.Tensor: shape=(32, 3, 4, 6), dtype=float32, numpy=
array([[[[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]]],


       [[[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.]]],


       [[[2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2.],
         [2., 2., 2