## TensorFlow Tensor Basics

2020.11.6

### Reference

https://www.tensorflow.org/api_docs/python/tf/Tensor

In [19]:
import numpy as np
import tensorflow as tf

In [ ]:
c = tf.constant([[1.0, 2.0, 3.0, 4.0]])
c = tf.range(10)
print(1 - c)
print(c[:2])

In [2]:
y_true = [_ for _ in range(10)]
y_true = tf.cast(y_true, tf.bool)  # Equivalent to that threshold=0.5
print(y_true)

tf.Tensor([False  True  True  True  True  True  True  True  True  True], shape=(10,), dtype=bool)


In [3]:
import tensorflow_addons as tfa

In [4]:
y_true = tf.constant([[1, 0, 1], [0, 1, 0]], dtype=tf.int32)
y_pred = tf.constant([[1, 0, 0], [0, 1, 1]], dtype=tf.int32)

In [7]:
output = tfa.metrics.MultiLabelConfusionMatrix(num_classes=3)
output.update_state(y_true, y_pred)
result = output.result().numpy()
print('Confusion matrix:', result)

Confusion matrix: [[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]]


In [10]:
result[0]

array([[1., 0.],
       [0., 1.]], dtype=float32)

In [18]:
y_true = np.asarray([1, 1, 0, 0])
y_true = np.vstack((y_true, 1-y_true))  # multi-dim pred array
y_true = y_true.T
y_true # n, n, p, p

array([[1, 0],
       [1, 0],
       [0, 1],
       [0, 1]])

In [20]:
y_pred = np.asarray([1, 0, 1, 1, 1])  # p, n, p, p, p
y_pred = np.vstack((y_pred, 1-y_pred))  # multi-dim pred array
y_pred = y_pred.T
y_pred # n, n, p, n # tn, tn, tp, fn

array([[1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [21]:
y_pred.shape

(5, 2)

In [24]:
class_id = 0
y_pred[..., class_id]

array([1, 0, 1, 1, 1])

## multi_label

## TensorFlow ops

In [30]:
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops

In [14]:
y_pred = [[1, 0, 1, 1, 1], [1, 0, 1, 1, 1]]
# data_tiles = [1, 1, 1]
data_tiles = [1, 1, 1]

In [22]:
predictions_extra_dim = array_ops.expand_dims(y_pred, 0)
preds_tiled = array_ops.tile(predictions_extra_dim, data_tiles)

In [23]:
predictions_extra_dim

<tf.Tensor: shape=(1, 5, 2), dtype=int32, numpy=
array([[[1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]]])>

In [17]:
preds_tiled

<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1]]])>

In [29]:
num_thresholds = 1
pred_shape = array_ops.shape(y_pred)
num_predictions = pred_shape[0]

thresh_pretile_shape = [num_thresholds, 1, -1]
thresh_tiles = [1, num_predictions, thresh_label_tile]
data_tiles = [num_thresholds, 1, 1]

NameError: name 'thresh_label_tile' is not defined

In [26]:
pred_is_pos = math_ops.greater(preds_tiled, thresh_tiled)

NameError: name 'thresh_tiled' is not defined