## TensorFlow Playground

2020.11.24

In [60]:
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import clip_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.framework import constant_op
from tensorflow.python.keras import backend_config
epsilon = backend_config.epsilon

In [51]:
e = epsilon()

In [52]:
print("%.15f" % e)

0.000000100000000


In [53]:
print("%.15f" % pow(2, -23))

0.000000119209290


In [55]:
def binary_cross_entropy(y_true, y_pred):
    y_true = tf.cast(y_true, dtype=tf.float32)
    y_pred = tf.cast(y_pred, dtype=tf.float32)

    epsilon_ = constant_op.constant(epsilon(), dtype=output.dtype.base_dtype)
    # or
    # from tensorflow.python.framework import ops
    # target = ops.convert_to_tensor_v2(target)
    # output = ops.convert_to_tensor_v2(output)

    bce = - y_true * math_ops.log(y_pred)
    bce += - (1-y_true) * math_ops.log(1-y_pred)
    return bce

In [3]:
def binary_cross_entropy_np(y_true, y_pred):
    bce = - y_true * np.log(y_pred)
    bce += - (1-y_true) * np.log(1-y_pred)
    return bce

In [4]:
tf.pow(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [5]:
tf.pow(0, 0)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
y_true = np.asarray([1., 0.])
y_pred = np.asarray([0.001, 0.999])
cross_entropy = - y_true * math_ops.log(y_pred)

In [73]:
positive_label_mask = tf.equal(y_true, 1.0)

In [74]:
positive_label_mask

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
y_true = np.asarray([1., 0.])

In [84]:
y_pred = np.asarray([[0., 1.], [0., 1.]])
y_pred = tf.cast(y_pred, dtype=tf.float32)
epsilon_ = constant_op.constant(epsilon(), dtype=y_pred.dtype.base_dtype)
y_pred_ones_mask = tf.equal(y_pred, 1.)
y_pred_zeros_mask = tf.equal(y_pred, 0.)
y_pred = tf.where(y_pred_ones_mask, clip_ops.clip_by_value(y_pred, epsilon_, 1. - epsilon_), y_pred)
y_pred = tf.where(y_pred_zeros_mask, clip_ops.clip_by_value(y_pred, epsilon_, 1. - epsilon_), y_pred)
y_pred

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.000000e-07, 9.999999e-01],
       [1.000000e-07, 9.999999e-01]], dtype=float32)>

In [77]:


y_true = tf.cast(y_true, dtype=tf.float32)
y_pred = tf.cast(y_pred, dtype=tf.float32)
epsilon_ = constant_op.constant(epsilon(), dtype=y_pred.dtype.base_dtype)
y_pred = clip_ops.clip_by_value(y_pred, epsilon_, 1. - epsilon_)
y_pred

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.000000e-07, 9.999999e-01], dtype=float32)>

In [67]:
binary_cross_entropy = - y_true * math_ops.log(y_pred)
binary_cross_entropy += - (1-y_true) * math_ops.log(1-y_pred)
binary_cross_entropy

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([16.118095, 15.942385], dtype=float32)>

In [68]:
binary_cross_entropy = - y_true * math_ops.log(y_pred)
binary_cross_entropy

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([16.118095,  0.      ], dtype=float32)>

In [70]:
binary_cross_entropy = - (1-y_true) * math_ops.log(1-y_pred)
binary_cross_entropy

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.      , 15.942385], dtype=float32)>

In [72]:
math_ops.log(y_pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.6118095e+01, -1.1920930e-07], dtype=float32)>

In [71]:
math_ops.log(1-y_pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.1920930e-07, -1.5942385e+01], dtype=float32)>

In [26]:
binary_cross_entropy[0] * 0

<tf.Tensor: shape=(), dtype=float64, numpy=nan>

In [11]:
probs_gt = tf.where(positive_label_mask, y_pred, 1.0 - y_pred)
probs_gt

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.001, 0.001])>

In [12]:
binary_cross_entropy_np(y_true, y_pred)

array([6.90775528, 6.90775528])

In [13]:
alpha = 0.99
gamma = 0

In [14]:
modulator = tf.pow(1.0 - probs_gt, gamma)
loss = modulator * binary_cross_entropy
weighted_loss = tf.where(positive_label_mask, alpha * loss, (1.0-alpha) * loss)

In [15]:
weighted_loss

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([6.83867773, 0.06907755])>