In [1]:
import torch

In [2]:
a = torch.randn(4, 4)

In [3]:
a

tensor([[-1.2827,  1.3665, -1.9922, -1.1368],
        [ 1.6375, -0.3285, -0.1040, -0.7760],
        [ 0.2677,  0.5194, -1.3841,  0.4916],
        [ 1.0384, -1.2769,  0.4705, -0.3047]])

In [5]:
torch.sum(a, 1) # 合并列

tensor([-3.0451,  0.4288, -0.1054, -0.0727])

In [6]:
torch.sum(a, 0) # 合并行

tensor([ 1.6609,  0.2805, -3.0099, -1.7259])