In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [39]:
# x is of size N x C = 3 x 5
x = torch.randn(3, 5, requires_grad=True)
target=torch.FloatTensor([[0,0,0,1,0],[0,1,0,0,0],[0,0,1,0,0]])

In [56]:
logits = F.sigmoid(x)
print(f"logits: {logits}")
bce_loss=nn.BCELoss()
bce_loss(logits, target)

logits: tensor([[0.2784, 0.2955, 0.3746, 0.4402, 0.6530],
        [0.6604, 0.4345, 0.9109, 0.3050, 0.6425],
        [0.3067, 0.7631, 0.7082, 0.4385, 0.3192]], grad_fn=<SigmoidBackward>)


tensor(0.7908, grad_fn=<BinaryCrossEntropyBackward>)

In [57]:
# logits = F.sigmoid(x)
logits = x
print(f"logits: {logits}")
bce_loss_with_logits=nn.BCEWithLogitsLoss() # contain Sigmoid logits
bce_loss_with_logits(x, target)

logits: tensor([[-0.9525, -0.8688, -0.5124, -0.2402,  0.6322],
        [ 0.6651, -0.2633,  2.3245, -0.8237,  0.5864],
        [-0.8156,  1.1698,  0.8868, -0.2472, -0.7575]], requires_grad=True)


tensor(0.7908, grad_fn=<MeanBackward1>)

In [53]:
# output = F.nll_loss(logits, target)
# print(f"output: {output}")
# output.backward()

In [58]:
# sigmoid activation then softmax output
logits = F.sigmoid(x)
logits = F.softmax(logits)
print(f"logits: {logits}")

logits: tensor([[0.1740, 0.1770, 0.1915, 0.2045, 0.2530],
        [0.2098, 0.1674, 0.2696, 0.1471, 0.2061],
        [0.1606, 0.2535, 0.2400, 0.1832, 0.1626]], grad_fn=<SoftmaxBackward>)


In [59]:
logits.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [62]:
logits[0]

tensor([0.1740, 0.1770, 0.1915, 0.2045, 0.2530], grad_fn=<SelectBackward>)

In [63]:
target[0]

tensor([0., 0., 0., 1., 0.])

In [61]:
# bce loss with above logits
bce_loss=nn.BCELoss()
bce_loss(logits[0], target[0])

tensor(0.4955, grad_fn=<BinaryCrossEntropyBackward>)

In [ ]:
# cce loss with above logits
cce_loss=nn.CrossEntropyLoss()
cce_loss(logits[0], target[0])